"""
Oracle Database Migration Script - Add Contact Messages Table
Creates contact_messages table for storing user contact form submissions
"""
import oracledb
import os
from getpass import getpass


def migrate_contact_messages():
    """Create contact_messages table in Oracle database"""

    print("=" * 70)
    print("DialSmart Oracle Database Migration")
    print("Adding Contact Messages Table")
    print("=" * 70)
    print()

    # Get Oracle connection details
    print("Enter Oracle Database Connection Details:")
    username = input("Username (default: ds_user): ").strip() or "ds_user"
    password = getpass("Password: ")
    host = input("Host (default: localhost): ").strip() or "localhost"
    port = input("Port (default: 1521): ").strip() or "1521"
    service_name = input("Service Name (default: orclpdb): ").strip() or "orclpdb"

    # Build connection string (DSN)
    dsn = f"{host}:{port}/{service_name}"

    try:
        # Connect to Oracle
        print(f"\nConnecting to Oracle at {host}:{port}/{service_name}...")
        connection = oracledb.connect(user=username, password=password, dsn=dsn)
        cursor = connection.cursor()
        print("✅ Connected successfully!")
        print()

        # Check if table already exists
        print("Checking if contact_messages table exists...")
        cursor.execute("""
            SELECT COUNT(*)
            FROM user_tables
            WHERE table_name = 'CONTACT_MESSAGES'
        """)

        table_exists = cursor.fetchone()[0] > 0

        if table_exists:
            print("✅ contact_messages table already exists!")
            print("No migration needed.")
            cursor.close()
            connection.close()
            return True

        # Create contact_messages table
        print("Creating contact_messages table...")
        print()

        create_table_sql = """
        CREATE TABLE contact_messages (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100) NOT NULL,
            email VARCHAR2(120) NOT NULL,
            subject VARCHAR2(200),
            message CLOB NOT NULL,
            is_read NUMBER(1) DEFAULT 0,
            is_replied NUMBER(1) DEFAULT 0,
            admin_reply CLOB,
            replied_by_id NUMBER,
            replied_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_replied_by FOREIGN KEY (replied_by_id)
                REFERENCES users(id) ON DELETE SET NULL
        )
        """

        cursor.execute(create_table_sql)
        print("✅ Table created successfully!")

        # Create indexes for better query performance
        print("Creating indexes...")

        # Index on email for faster lookups
        cursor.execute("""
            CREATE INDEX idx_contact_messages_email
            ON contact_messages(email)
        """)

        # Index on is_read for filtering unread messages
        cursor.execute("""
            CREATE INDEX idx_contact_messages_is_read
            ON contact_messages(is_read)
        """)

        # Index on is_replied for filtering pending replies
        cursor.execute("""
            CREATE INDEX idx_contact_messages_is_replied
            ON contact_messages(is_replied)
        """)

        # Index on created_at for sorting by date
        cursor.execute("""
            CREATE INDEX idx_contact_messages_created_at
            ON contact_messages(created_at)
        """)

        print("✅ Indexes created successfully!")

        # Create trigger for updated_at
        print("Creating trigger for updated_at column...")
        cursor.execute("""
            CREATE OR REPLACE TRIGGER contact_messages_update_trigger
            BEFORE UPDATE ON contact_messages
            FOR EACH ROW
            BEGIN
                :NEW.updated_at := CURRENT_TIMESTAMP;
            END;
        """)
        print("✅ Trigger created successfully!")

        # Commit all changes
        connection.commit()

        print()
        print("=" * 70)
        print("✅ Contact Messages Table Migration Completed Successfully!")
        print("=" * 70)
        print()
        print("Created:")
        print("  ✅ contact_messages table")
        print("  ✅ 4 indexes for performance")
        print("  ✅ Trigger for auto-updating updated_at")
        print()
        print("📝 Features:")
        print("  - Store contact form submissions")
        print("  - Track read/unread status")
        print("  - Track reply status")
        print("  - Store admin replies")
        print("  - Automatic timestamps")

        cursor.close()
        connection.close()

        return True

    except oracledb.Error as e:
        print()
        print(f"❌ Oracle Error: {e}")
        print()
        return False
    except Exception as e:
        print()
        print(f"❌ Error: {str(e)}")
        print()
        return False


if __name__ == '__main__':
    try:
        success = migrate_contact_messages()

        if success:
            print()
            print("✅ Migration successful!")
            print()
            print("Next steps:")
            print("1. Restart your Flask application: python run.py")
            print("2. Test the contact form at /contact")
            print("3. View messages at /admin/messages")
        else:
            print()
            print("❌ Migration failed! Please check the errors above.")

    except KeyboardInterrupt:
        print("\n\n❌ Migration cancelled by user.")
    except ImportError:
        print()
        print("❌ oracledb not installed!")
        print()
        print("Please install it:")
        print("  pip install oracledb")
        print()
    except Exception as e:
        print()
        print(f"❌ Unexpected error: {str(e)}")
        print()
